name: shadowsocks
version: '1.20151028'
synopsis: A fast SOCKS5 proxy that help you get through firewalls
description: ! 'Shadowsocks implemented in Haskell. Original python version: <https://github.com/clowwindy/shadowsocks>'
category: Web
author: rnons
maintainer: remotenonsense@gmail.com
license: MIT
homepage: https://github.com/rnons/shadowsocks-haskell
git: git://github.com/rnons/shadowsocks-haskell.git
bug-reports: https://github.com/rnons/shadowsocks-haskell/issues
tested-with: GHC==7.10.2
dependencies:
  - base ==4.*
  - bytestring
  - pipes
library:
  source-dirs: src
  exposed-modules:
    - Shadowsocks.Encrypt
    - Shadowsocks.Util
  dependencies:
    - aeson
    - binary
    - containers
    - cryptohash
    - directory
    - HsOpenSSL
    - iproute
    - network
    - optparse-applicative
    - unordered-containers
executables:
  ssserver: &exe
    main: server.hs
    source-dirs: app
    other-extensions:
      - OverloadedStrings
      - DeriveGeneric
    dependencies:
      - shadowsocks
      - async
      - pipes-bytestring
      - pipes-network
      - network
      - network-simple
      - socks
      - streaming-commons
    ghc-options:
      - -O2
      - -threaded
  sslocal:
    <<: *exe
    main: local.hs

tests:
  test:
    main: test.hs
    ghc-options:
      - -Wall
    dependencies:
      - binary
      - containers
      - cryptohash
      - process
      - HUnit
data-files:
  - config.json
